# Generated by Django 3.2.3 on 2021-06-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('imageurl', models.CharField(max_length=1000)),
                ('targetUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
